default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: WarzoneRegistration_development

test:
  <<: *default
  database: WarzoneRegistration_test

production:
  <<: *default
  database: WarzoneRegistration_production
  username: WarzoneRegistration
  password: <%= ENV['WarzoneRegistration_DATABASE_PASSWORD'] %>
